// ドメイン（JPA エンティティ）のテストパッケージ
package com.izumacha.expensetracker.domain;

// 列の定義（名前・長さ・NOT NULL）を読み取るためのアノテーション
import jakarta.persistence.Column;
// 列挙をどの形式で保存するかを読み取るためのアノテーション
import jakarta.persistence.Enumerated;
// 列挙の保存形式（文字列か序数か）を表す列挙
import jakarta.persistence.EnumType;
// 主キーであることを判定するためのアノテーション
import jakarta.persistence.Id;
// テーブル名とインデックス定義を読み取るためのアノテーション
import jakarta.persistence.Table;
// エンティティのフィールドを走査するためのリフレクション型
import java.lang.reflect.Field;
// フィールドの修飾子（static かどうか）を判定するためのユーティリティ
import java.lang.reflect.Modifier;
// README を読むためのファイル入出力ユーティリティ
import java.nio.file.Files;
// README のパスを表す型
import java.nio.file.Path;
// 読み込み時の文字コードを明示するための型
import java.nio.charset.StandardCharsets;
// 日時列の型判定に使う
import java.time.LocalDateTime;
// 解析結果を集める入れ物
import java.util.ArrayList;
// 解析結果を名前で引くための入れ物
import java.util.LinkedHashMap;
// 解析結果の一覧を扱うインターフェース
import java.util.List;
// 名前で引ける解析結果を扱うインターフェース
import java.util.Map;
// 全テストの前に 1 度だけ実行する準備メソッドを宣言するアノテーション
import org.junit.jupiter.api.BeforeAll;
// テストメソッドを宣言するアノテーション
import org.junit.jupiter.api.Test;

// 検証用の assertThat を取り込む（AssertJ）
import static org.assertj.core.api.Assertions.assertThat;

/**
 * README に載せた {@code audit_logs} の手書き DDL が、{@link AuditLog} の定義とずれていないことを
 * 機械的に保証する整合性テスト。
 *
 * <p>【何を守るテストか】本番のスキーマ方針は {@code ddl-auto: validate}（DDL を自動発行しない）
 * なので、既存の本番 DB へ監査ログを導入するときは README の DDL を<b>人手で適用する</b>。
 * README 自身が「列を増やしたら両方を同じ PR で直してください」と書いているとおり、この写しは
 * 人の記憶だけで正本（{@link AuditLog}）に追随している。ずれると次の 2 通りに壊れる。
 *
 * <ul>
 *   <li><b>列のずれ</b>: 起動時の {@code validate} が食い違いを検出して<b>本番の起動が失敗する</b>。
 *       安全側に倒れるとはいえ、気付くのがデプロイの瞬間で、しかもローカル（{@code docker compose}）と
 *       Testcontainers はスキーマを自動生成するため<b>手元では絶対に再現しない</b>。</li>
 *   <li><b>インデックスのずれ</b>: {@code validate} はインデックスを検証しない。README への追記を
 *       忘れると、本番だけインデックスが無いまま<b>静かに</b>動き続ける。{@code audit_logs} は追記のみで
 *       際限なく増えるテーブルなので、参照が全件走査に落ちて後から効いてくる（共通規約 §8）。</li>
 * </ul>
 *
 * <p>前者は「起動が失敗する」ことで気付けるが後者は気付けない。どちらも、写しを人手で追随させる
 * かぎり必ず起こりうるため、{@code AuditedEntityCoverageTest} と同じ考え方で検出網を置く
 * ——人の付け忘れをビルドで止める。
 *
 * <p>DB も Spring コンテキストも起動せず、README の読み取りとリフレクションだけで完結する（§11）。
 */
class AuditLogReadmeDdlTest {

    /**
     * 読み取る README のパス。
     *
     * <p>Surefire はプロジェクト直下を作業ディレクトリにして実行するため相対パスで解決できる。
     */
    private static final Path README_PATH = Path.of("README.md");

    /**
     * 解析対象の DDL を README の中から見つけるための目印。
     *
     * <p><b>テーブル名をここに含めない</b>のが要点。含めてしまうと、README のテーブル名を変えた
     * ときにブロックが見つからず「README に DDL が無い」という的外れな失敗になるか、前方一致で
     * 別名（{@code audit_logs_v2} など）を掴んで<b>素通りする</b>。テーブル名は正本（{@code @Table}）
     * から取り、それと一致する文を探す方式にする（{@link #readDdlBlock()}）。
     */
    private static final String CREATE_TABLE_MARKER = "CREATE TABLE";

    // Markdown のコードフェンス（DDL ブロックの終わりを示す）
    private static final String CODE_FENCE = "```";

    // インデックス定義の文であることを見分けるための接頭辞（一意インデックスは UNIQUE が挟まる）
    private static final String CREATE_MARKER = "CREATE";

    // 一意インデックスであることを示す語
    private static final String UNIQUE_MARKER = "UNIQUE";

    // インデックス定義であることを示す語
    private static final String INDEX_MARKER = "INDEX";

    // @Column の length 属性の既定値（JPA 仕様。属性を書かなかった列の期待長として使う）
    private static final int DEFAULT_COLUMN_LENGTH = 255;

    /**
     * README から読み取って解析した DDL（列定義）。
     *
     * <p>README は 1 回の実行中に変わらないため、テストごとに読み直さず {@link #parseReadmeDdl()} で
     * 一度だけ読み解く。読み取り・解析の失敗も 1 回の明確なエラーとして出る（各テストで 5 回
     * 同じ失敗が並ばない）。
     */
    private static Map<String, DdlColumn> ddlColumns;

    // README から読み取って解析した DDL（インデックス定義）
    private static List<DdlIndex> ddlIndexes;

    /**
     * README の DDL から読み取った 1 列分の定義。
     *
     * @param name       列名（小文字に正規化済み）
     * @param type       型（小文字に正規化済み。例 {@code varchar(64)}）
     * @param notNull    {@code NOT NULL} が付いているか
     * @param primaryKey {@code PRIMARY KEY} が付いているか
     * @param identity   {@code GENERATED BY DEFAULT AS IDENTITY}（自動採番）が付いているか
     */
    private record DdlColumn(String name, String type, boolean notNull, boolean primaryKey, boolean identity) {
    }

    /**
     * インデックス 1 つ分の定義（README 側の読み取り結果と、エンティティ側の期待値の両方に使う）。
     *
     * @param name    インデックス名（小文字に正規化済み）
     * @param columns 対象の列名（小文字に正規化済み・定義された順）
     * @param unique  一意インデックス（{@code CREATE UNIQUE INDEX}）か
     */
    private record DdlIndex(String name, List<String> columns, boolean unique) {
    }

    /**
     * {@link AuditLog} の注釈から起こした 1 列分の期待値。
     *
     * @param name    期待する列名
     * @param type    期待する型（小文字。例 {@code varchar(64)}）
     * @param notNull {@code NOT NULL} であるべきか
     * @param id      主キーの列か
     */
    private record ExpectedColumn(String name, String type, boolean notNull, boolean id) {
    }

    // ------------------------------------------------------------------
    // README 側の読み取り
    // ------------------------------------------------------------------

    /**
     * README から DDL のコードブロック（CREATE TABLE ＋ CREATE INDEX）だけを切り出して返す。
     *
     * <p><b>探し方</b>: README 中の {@code CREATE TABLE} をすべて見て、テーブル名が正本
     * （{@code AuditLog} の {@code @Table}）と<b>完全一致</b>する文を採用する。README に別のテーブルの
     * DDL が増えても取り違えず、逆に README 側でテーブル名を変えた（＝正本とずれた）場合は
     * 「見つからない」として落ちる。前方一致で探すと {@code audit_logs_v2} のような別名を掴んで
     * しまい、テーブル名のずれを検出できなくなる。
     */
    private static String readDdlBlock() {
        // README を読む（存在しない・読めないのは環境の異常なので握り潰さず失敗させる。§6）
        String readme;
        try {
            // UTF-8 として README 全体を読み込む
            readme = Files.readString(README_PATH, StandardCharsets.UTF_8);
        } catch (java.io.IOException e) {
            // どのファイルが読めなかったかを添えて停止する
            throw new IllegalStateException("README を読み取れません: " + README_PATH.toAbsolutePath(), e);
        }
        // 正本のテーブル名を取り出す（この名前の CREATE TABLE だけを採用する）
        String expectedTable = tableAnnotation().name();
        // 最初の CREATE TABLE を探す
        int cursor = readme.indexOf(CREATE_TABLE_MARKER);
        // 見つからなくなるまで 1 文ずつ確認する
        while (cursor >= 0) {
            // 列定義を囲む丸括弧の開き位置を探す（テーブル名はこの手前にある）
            int paren = readme.indexOf('(', cursor);
            // 開き括弧が無ければこれ以上たどれないので打ち切る
            if (paren < 0) {
                // 探索を終える
                break;
            }
            // 「CREATE TABLE」と開き括弧の間にある語をテーブル名として取り出す
            String tableName = readme.substring(cursor + CREATE_TABLE_MARKER.length(), paren).trim();
            // 正本と完全に一致したらこの文が目的の DDL
            if (tableName.equals(expectedTable)) {
                // DDL ブロックの終わり（次のコードフェンス）を探す
                int end = readme.indexOf(CODE_FENCE, cursor);
                // 閉じフェンスが無ければ Markdown が壊れているので失敗させる
                assertThat(end)
                        // 失敗時に何が起きたかを示す
                        .as("README の DDL ブロックを閉じるコードフェンス（%s）が見つかりません", CODE_FENCE)
                        // 見つかった位置は 0 以上になる
                        .isNotNegative();
                // 開始位置から閉じフェンスの手前までを DDL 本体として返す
                return readme.substring(cursor, end);
            }
            // 一致しなければ次の CREATE TABLE を探す
            cursor = readme.indexOf(CREATE_TABLE_MARKER, cursor + CREATE_TABLE_MARKER.length());
        }
        // 正本のテーブル名を持つ DDL が無い＝本番への適用手順が失われている（またはテーブル名がずれた）
        throw new IllegalStateException(
                // 何が無くて、どう直せばよいかを示す
                "README に「" + CREATE_TABLE_MARKER + " " + expectedTable + "」が見つかりません"
                        + "（本番へ手動適用する DDL が失われていないか、テーブル名が @Table とずれていないか確認してください）");
    }

    /** README を 1 度だけ読み解き、以降のテストが使う解析結果を用意する。 */
    @BeforeAll
    static void parseReadmeDdl() {
        // README から DDL ブロックを切り出す
        String ddl = readDdlBlock();
        // 列定義を解析して保持する
        ddlColumns = parseColumns(ddl);
        // インデックス定義を解析して保持する
        ddlIndexes = parseIndexes(ddl);
    }

    /** DDL の {@code CREATE TABLE} 部分を解析し、列名から定義を引ける形にして返す。 */
    private static Map<String, DdlColumn> parseColumns(String ddl) {
        // CREATE TABLE の列定義を囲む丸括弧の開き位置を探す
        int open = ddl.indexOf('(');
        // 開き括弧が無ければ DDL の形が想定と違うので失敗させる
        assertThat(open)
                // 失敗時に何が起きたかを示す
                .as("CREATE TABLE の列定義を囲む丸括弧が見つかりません")
                // 見つかった位置は 0 以上になる
                .isNotNegative();
        // 開き括弧に対応する閉じ括弧を探す（入れ子の括弧に耐えるため深さを数える）
        int close = matchingParenthesis(ddl, open);
        // 括弧の内側（列定義の並び）を取り出す
        String body = ddl.substring(open + 1, close);
        // 解析結果を列名で引けるようにする入れ物（定義順を保つ）
        Map<String, DdlColumn> columns = new LinkedHashMap<>();
        // 括弧の深さ 0 のカンマで区切って 1 列ずつ処理する
        for (String definition : splitTopLevel(body)) {
            // 前後の空白を落とす
            String trimmed = definition.trim();
            // 空の要素（末尾のカンマなど）は列ではないので飛ばす
            if (trimmed.isEmpty()) {
                // 次の要素へ進む
                continue;
            }
            // 空白の連続で区切って語に分ける（VARCHAR(64) のように括弧が続く語は 1 語のまま残る）
            String[] tokens = trimmed.split("\\s+");
            // 「列名」「型」の 2 語は最低限必要なので、足りなければ解析できていない
            assertThat(tokens.length)
                    // 失敗時にどの定義でつまずいたかを示す
                    .as("列定義を解析できません（列名と型が読み取れません）: %s", trimmed)
                    // 2 語以上あることを検証する
                    .isGreaterThanOrEqualTo(2);
            // 1 語目が列名（大文字小文字の違いを無視するため小文字にそろえる）
            String name = tokens[0].toLowerCase();
            // 2 語目が型（同じく小文字にそろえる）
            String type = tokens[1].toLowerCase();
            // 3 語目以降の修飾子を 1 つの文字列にまとめる（大文字にそろえて含有判定しやすくする）
            StringBuilder modifiers = new StringBuilder();
            // 3 語目から末尾までを連結する
            for (int i = 2; i < tokens.length; i++) {
                // 語の区切りが消えないよう空白を挟んでから連結する
                modifiers.append(' ').append(tokens[i].toUpperCase());
            }
            // 連結した修飾子を文字列として確定する
            String modifierText = modifiers.toString();
            // 解析した 1 列分を入れ物へ登録する
            columns.put(name, new DdlColumn(
                    // 列名
                    name,
                    // 型
                    type,
                    // NOT NULL が付いているか
                    modifierText.contains("NOT NULL"),
                    // PRIMARY KEY が付いているか
                    modifierText.contains("PRIMARY KEY"),
                    // 自動採番（識別列）として定義されているか
                    modifierText.contains("GENERATED BY DEFAULT AS IDENTITY")));
        }
        // 解析結果を返す
        return columns;
    }

    /**
     * DDL のインデックス定義（{@code CREATE INDEX} / {@code CREATE UNIQUE INDEX}）をすべて解析して返す。
     *
     * <p>一意インデックスも読めるようにしてあるのは、{@code @Index(unique = true)} を足したときに
     * 正しい README の書き方（{@code CREATE UNIQUE INDEX}）がこの検証を通せないと、<b>まっとうな
     * スキーマ変更のたびにテスト側を直さないと進めなくなる</b>ため。逆向き（README にだけ
     * 一意インデックスが残る）も見逃さない。
     */
    private static List<DdlIndex> parseIndexes(String ddl) {
        // 解析結果を集める入れ物
        List<DdlIndex> indexes = new ArrayList<>();
        // 対象のテーブル名（インデックスが別のテーブルに向いていないかの確認に使う）
        String expectedTable = tableAnnotation().name();
        // CREATE TABLE の列定義を読み飛ばすため、その閉じ括弧の位置を求める
        int tableClose = matchingParenthesis(ddl, ddl.indexOf('('));
        // 閉じ括弧より後ろ（インデックス定義が並ぶ範囲）を「;」で文に分けて 1 つずつ処理する
        for (String rawStatement : ddl.substring(tableClose).split(";")) {
            // 前後の空白を落とす
            String statement = rawStatement.trim();
            // インデックス定義でない断片（閉じ括弧だけの行など）は飛ばす
            if (!statement.toUpperCase().startsWith(CREATE_MARKER)) {
                // 次の文へ進む
                continue;
            }
            // 対象列を囲む丸括弧の開き位置を探す
            int open = statement.indexOf('(');
            // 開き括弧が無ければ文の形が想定と違うので失敗させる
            assertThat(open)
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義の対象列を囲む丸括弧が見つかりません: %s", statement)
                    // 見つかった位置は 0 以上になる
                    .isNotNegative();
            // 開き括弧に対応する閉じ括弧を探す
            int close = matchingParenthesis(statement, open);
            // 「CREATE [UNIQUE] INDEX <名前> ON <テーブル>」の部分を語に分ける
            String[] head = statement.substring(0, open).trim().split("\\s+");
            // 2 語目が UNIQUE なら一意インデックス（以降の語の位置が 1 つずれる）
            boolean unique = head.length > 1 && head[1].equalsIgnoreCase(UNIQUE_MARKER);
            // UNIQUE の有無による語の位置ずれ
            int offset = unique ? 1 : 0;
            // CREATE / [UNIQUE] / INDEX / 名前 / ON / テーブル名 の語数を検証する
            assertThat(head.length)
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義を解析できません: %s", statement)
                    // UNIQUE の有無に応じた語数であることを検証する
                    .isEqualTo(5 + offset);
            // 3 語目（UNIQUE があれば 4 語目）が INDEX であることを検証する
            assertThat(head[1 + offset])
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義として解釈できない文です: %s", statement)
                    // INDEX という語であることを検証する
                    .isEqualToIgnoringCase(INDEX_MARKER);
            // インデックスが正本のテーブルに向いていることを検証する
            assertThat(head[4 + offset])
                    // 失敗時にどのテーブルへ向いていたかを示す
                    .as("インデックス %s が別のテーブルに向いています: %s", head[2 + offset], statement)
                    // 対象テーブル名が一致することを検証する
                    .isEqualTo(expectedTable);
            // 対象列の一覧を組み立てる入れ物
            List<String> indexColumns = new ArrayList<>();
            // 括弧の内側をカンマで区切って 1 列ずつ加える
            for (String column : splitTopLevel(statement.substring(open + 1, close))) {
                // 前後の空白を落とし小文字にそろえて加える
                indexColumns.add(column.trim().toLowerCase());
            }
            // 解析した 1 つ分を入れ物へ加える
            indexes.add(new DdlIndex(head[2 + offset].toLowerCase(), indexColumns, unique));
        }
        // 解析結果を返す
        return indexes;
    }

    /**
     * {@code open} の位置にある開き括弧に対応する閉じ括弧の位置を返す。
     *
     * <p>単純に最初の {@code ')'} を探すと、{@code NUMERIC(10, 2)} のように型が括弧を持つ列が
     * 増えたときに途中で切れる。深さを数えて対応する側を見つける。
     */
    private static int matchingParenthesis(String text, int open) {
        // 括弧の深さ（開き括弧で増やし閉じ括弧で減らす）
        int depth = 0;
        // 開き括弧の位置から末尾まで 1 文字ずつ走査する
        for (int i = open; i < text.length(); i++) {
            // 現在位置の文字を取り出す
            char c = text.charAt(i);
            // 開き括弧なら深さを 1 つ増やす
            if (c == '(') {
                // 深さを増やす
                depth++;
            } else if (c == ')') {
                // 閉じ括弧なら深さを 1 つ減らす
                depth--;
                // 深さが 0 に戻った位置が対応する閉じ括弧
                if (depth == 0) {
                    // その位置を返す
                    return i;
                }
            }
        }
        // 対応する閉じ括弧が無いのは DDL が壊れているので握り潰さず失敗させる（§6）
        throw new IllegalStateException("対応する閉じ括弧が見つかりません: " + text.substring(open));
    }

    /**
     * 括弧の深さ 0 にあるカンマだけで文字列を区切って返す。
     *
     * <p>{@code String.split(",")} だと型の中のカンマ（{@code NUMERIC(10, 2)}）でも切れてしまうため、
     * 深さを見ながら自前で区切る。
     */
    private static List<String> splitTopLevel(String text) {
        // 区切った結果を集める入れ物
        List<String> parts = new ArrayList<>();
        // 括弧の深さ
        int depth = 0;
        // 直前の区切り位置
        int start = 0;
        // 先頭から末尾まで 1 文字ずつ走査する
        for (int i = 0; i < text.length(); i++) {
            // 現在位置の文字を取り出す
            char c = text.charAt(i);
            // 開き括弧なら深さを増やす
            if (c == '(') {
                // 深さを増やす
                depth++;
            } else if (c == ')') {
                // 閉じ括弧なら深さを減らす
                depth--;
            } else if (c == ',' && depth == 0) {
                // 深さ 0 のカンマは要素の区切りなので、そこまでを 1 要素として切り出す
                parts.add(text.substring(start, i));
                // 次の要素の開始位置を更新する
                start = i + 1;
            }
        }
        // 最後の区切りから末尾までを最終要素として加える
        parts.add(text.substring(start));
        // 区切った結果を返す
        return parts;
    }

    // ------------------------------------------------------------------
    // エンティティ側（正本）の読み取り
    // ------------------------------------------------------------------

    /** {@link AuditLog} の注釈から、DDL に現れるべき列の期待値を組み立てて返す。 */
    private static List<ExpectedColumn> expectedColumns() {
        // 期待値を集める入れ物
        List<ExpectedColumn> expected = new ArrayList<>();
        // エンティティが宣言しているフィールドを 1 つずつ確認する
        for (Field field : AuditLog.class.getDeclaredFields()) {
            // 定数（static）やコンパイラが足したフィールドは列ではないので飛ばす
            if (Modifier.isStatic(field.getModifiers()) || field.isSynthetic()) {
                // 次のフィールドへ進む
                continue;
            }
            // 列の設定（名前・長さ・NULL 可否）を取り出す（付いていなければ null）
            Column column = field.getAnnotation(Column.class);
            // 主キーの列かどうかを判定する
            boolean isId = field.isAnnotationPresent(Id.class);
            // 列名を決める（@Column で明示されていればそれ、無ければフィールド名を snake_case にした名前）
            String name = (column != null && !column.name().isEmpty())
                    // 明示された列名を使う
                    ? column.name()
                    // 明示が無いときは Spring Boot 既定の命名規則（キャメルケース→スネークケース）に合わせる
                    : camelCaseToSnakeCase(field.getName());
            // NOT NULL であるべきかを決める（主キーは PRIMARY KEY が NOT NULL を含むので必ず非 NULL）
            boolean notNull = isId || (column != null && !column.nullable());
            // 期待値を 1 件加える
            expected.add(new ExpectedColumn(name, expectedSqlType(field, column), notNull, isId));
        }
        // 組み立てた期待値を返す
        return expected;
    }

    /**
     * フィールドの Java 型から、DDL に書かれているべき SQL の型を決める。
     *
     * <p>対応表に無い型が現れたら黙って素通りさせず失敗させる。素通りさせると、新しい型の列を
     * 足した人に対して<b>この検出網が何も言わなくなる</b>（＝ README への追記漏れを見逃す）。
     */
    private static String expectedSqlType(Field field, Column column) {
        // 文字列系の列長を決める（@Column が無ければ JPA 既定の 255）
        int length = (column != null) ? column.length() : DEFAULT_COLUMN_LENGTH;
        // フィールドの型を取り出す
        Class<?> type = field.getType();
        // 文字列はそのまま可変長文字列になる
        if (type == String.class) {
            // 長さ付きの varchar を返す
            return "varchar(" + length + ")";
        }
        // 列挙は EnumType.STRING のときだけ可変長文字列になる（序数保存は数値列になり型が変わる）
        if (type.isEnum()) {
            // 保存形式の指定を取り出す
            Enumerated enumerated = field.getAnnotation(Enumerated.class);
            // 文字列として保存する指定であることを確かめる
            assertThat(enumerated != null && enumerated.value() == EnumType.STRING)
                    // 失敗時にどのフィールドかと理由を示す
                    .as("%s は @Enumerated(EnumType.STRING) ではありません（序数保存は監査ログとして成立しません）",
                            field.getName())
                    // 文字列保存であることを検証する
                    .isTrue();
            // 長さ付きの varchar を返す
            return "varchar(" + length + ")";
        }
        // 64 ビット整数は bigint になる
        if (type == Long.class || type == long.class) {
            // bigint を返す
            return "bigint";
        }
        // 日時は既定の精度（マイクロ秒）付きの timestamp になる
        if (type == LocalDateTime.class) {
            // timestamp(6) を返す
            return "timestamp(6)";
        }
        // 対応表に無い型は、期待する SQL 型が分からないまま検証を素通りさせないよう失敗させる
        throw new IllegalStateException(
                // どのフィールドで、何をすればよいかを示す
                "SQL 型の対応が未定義です: field=" + field.getName() + ", type=" + type.getName()
                        + "（AuditLogReadmeDdlTest#expectedSqlType に対応を追加してください）");
    }

    /** キャメルケースのフィールド名を、Spring Boot 既定の命名規則と同じスネークケースに変換する。 */
    private static String camelCaseToSnakeCase(String fieldName) {
        // 変換後の名前を組み立てるバッファ
        StringBuilder converted = new StringBuilder();
        // 先頭から末尾まで 1 文字ずつ走査する
        for (int i = 0; i < fieldName.length(); i++) {
            // 現在位置の文字を取り出す
            char c = fieldName.charAt(i);
            // 大文字は単語の切れ目なので、先頭以外ならアンダースコアを挟む
            if (Character.isUpperCase(c) && i > 0) {
                // 区切りのアンダースコアを加える
                converted.append('_');
            }
            // 文字自体は小文字にして加える
            converted.append(Character.toLowerCase(c));
        }
        // 変換した名前を返す
        return converted.toString();
    }

    /** {@link AuditLog} に宣言されている {@code @Table} の設定を返す。 */
    private static Table tableAnnotation() {
        // テーブル定義の注釈を取り出す
        Table table = AuditLog.class.getAnnotation(Table.class);
        // 付いていなければテーブル名もインデックスも読み取れないので失敗させる
        assertThat(table)
                // 失敗時に何が起きたかを示す
                .as("AuditLog に @Table が付いていません（テーブル名とインデックスの正本が失われています）")
                // 注釈が存在することを検証する
                .isNotNull();
        // 取り出した注釈を返す
        return table;
    }

    // ------------------------------------------------------------------
    // 検証
    // ------------------------------------------------------------------

    // 解析そのものが機能していること（空振りで素通りしていないこと）を検証する
    @Test
    void READMEのDDLを解析できている() {
        // 列定義が読み取れていることを検証する。
        // 【なぜ先に確かめるか】解析に失敗して 0 件になると、以降の「全部そろっている」検証が
        // 「対象なし」で常に成功し、検出網そのものが死んでいることに気付けなくなる。
        // なお、正本のテーブル名を持つ CREATE TABLE が README に無い場合は、この時点より前
        // （readDdlBlock）で明示的に失敗している
        assertThat(ddlColumns)
                // 失敗時に何が起きたかを示す
                .as("README の DDL から列定義を読み取れませんでした")
                // 少なくとも 1 列は読み取れていることを検証する
                .isNotEmpty();
        // インデックス定義も読み取れていることを検証する
        assertThat(ddlIndexes)
                // 失敗時に何が起きたかを示す
                .as("README の DDL からインデックス定義を読み取れませんでした")
                // 少なくとも 1 つは読み取れていることを検証する
                .isNotEmpty();
    }

    // エンティティの全列が README の DDL に同じ型・同じ NULL 可否で載っていることを検証する
    @Test
    void READMEのDDLがエンティティの全列を同じ定義で持つ() {
        // エンティティ側の期待値を 1 列ずつ突き合わせる
        for (ExpectedColumn expected : expectedColumns()) {
            // 同名の列を README 側から探す
            DdlColumn actual = ddlColumns.get(expected.name());
            // 列そのものが載っていることを検証する
            assertThat(actual)
                    // 失敗時にどの列が抜けているかと直し方を示す
                    .as("README の DDL に列 %s がありません（AuditLog に追加した列を README にも反映してください）",
                            expected.name())
                    // 列が存在することを検証する
                    .isNotNull();
            // 型が一致していることを検証する（列長のずれもここで落ちる）
            assertThat(actual.type())
                    // 失敗時にどの列でどうずれているかを示す
                    .as("README の DDL の列 %s の型がエンティティの定義と一致しません", expected.name())
                    // 期待する SQL 型と一致することを検証する
                    .isEqualTo(expected.type());
            // NULL 可否が一致していることを検証する。
            // PRIMARY KEY は SQL の定義上 NOT NULL を含むため、主キー列に NOT NULL を重ねて
            // 書いていなくても非 NULL とみなす（README は重複を避けて PRIMARY KEY だけを書いている）
            assertThat(actual.notNull() || actual.primaryKey())
                    // 失敗時にどの列でどうずれているかを示す
                    .as("README の DDL の列 %s の NOT NULL がエンティティの nullable と一致しません",
                            expected.name())
                    // 期待する NULL 可否と一致することを検証する
                    .isEqualTo(expected.notNull());
        }
    }

    // README の DDL にエンティティが持たない列が紛れていないことを検証する
    @Test
    void READMEのDDLに余分な列が無い() {
        // エンティティ側の列名を組み立てる
        List<String> expectedNames = expectedColumns().stream().map(ExpectedColumn::name).toList();
        // 【なぜ余分も見るか】列を削ったのに README に残っていると、validate では検出されず
        // （余分な列があってもエンティティ側の検証は通る）、使われない列が本番だけに残り続ける
        assertThat(ddlColumns.keySet())
                // 失敗時に何が起きているかを示す
                .as("README の DDL にエンティティが持たない列が含まれています")
                // 過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(expectedNames);
    }

    // 主キーが自動採番の識別列として定義されていることを検証する
    @Test
    void READMEのDDLの主キーが自動採番の識別列になっている() {
        // エンティティ側で主キーとされている列を探す
        ExpectedColumn idColumn = expectedColumns().stream()
                // 主キーの列だけに絞る
                .filter(ExpectedColumn::id)
                // 最初の 1 件を取り出す
                .findFirst()
                // 主キーが無いエンティティはこのテーブルでは想定していないので失敗させる
                .orElseThrow(() -> new IllegalStateException("AuditLog に @Id の列がありません"));
        // README 側の同名の列を取り出す
        DdlColumn actual = ddlColumns.get(idColumn.name());
        // 列そのものが載っていることを先に検証する。
        // 【なぜ先に見るか】無いまま次の行で参照すると、直し方の書かれていない NullPointerException が
        // 出るだけになり、読み手はスタックトレースから原因を推測することになる
        assertThat(actual)
                // 失敗時にどの列が抜けているかと直し方を示す
                .as("README の DDL に主キーの列 %s がありません（AuditLog の @Id を README にも反映してください）",
                        idColumn.name())
                // 列が存在することを検証する
                .isNotNull();
        // 主キー指定が付いていることを検証する
        assertThat(actual.primaryKey())
                // 失敗時に何が足りないかを示す
                .as("README の DDL の列 %s に PRIMARY KEY がありません", idColumn.name())
                // PRIMARY KEY が付いていることを検証する
                .isTrue();
        // 自動採番（識別列）として定義されていることを検証する。
        // 【なぜ確かめるか】@GeneratedValue(IDENTITY) は DB 側の採番が前提で、識別列でないと
        // 挿入時に主キーが埋まらず、監査ログの書き込みだけが本番で落ちる（しかも fail-open なので
        // WARN が出るだけで API は正常に見える）
        assertThat(actual.identity())
                // 失敗時に何が足りないかを示す
                .as("README の DDL の列 %s が GENERATED BY DEFAULT AS IDENTITY になっていません",
                        idColumn.name())
                // 識別列として定義されていることを検証する
                .isTrue();
    }

    // エンティティが宣言するインデックスが README の DDL と過不足なく一致することを検証する
    @Test
    void READMEのDDLがエンティティの全インデックスを過不足なく持つ() {
        // エンティティ側の期待値を組み立てる入れ物
        List<DdlIndex> expected = new ArrayList<>();
        // @Table のインデックス宣言を 1 つずつ期待値へ変換する
        for (jakarta.persistence.Index index : tableAnnotation().indexes()) {
            // 対象列（"a, b" の形）を組み立てる入れ物
            List<String> indexColumns = new ArrayList<>();
            // カンマ区切りの列名を 1 つずつ加える
            for (String column : index.columnList().split(",")) {
                // 前後の空白を落とし小文字にそろえて加える
                indexColumns.add(column.trim().toLowerCase());
            }
            // 期待値を 1 件加える（一意指定の有無も比較対象に含める）
            expected.add(new DdlIndex(index.name().toLowerCase(), indexColumns, index.unique()));
        }
        // 【なぜ過不足の両方を見るか】ddl-auto: validate はインデックスを検証しないため、
        // ここでずれても本番は起動してしまう。追記漏れは全件走査に、消し忘れは不要な
        // 書き込みコストになり、どちらも実行時には何の合図も出ない
        assertThat(ddlIndexes)
                // 失敗時に何が起きているかと直し方を示す
                .as("README の DDL のインデックスが @Table の宣言と一致しません"
                        + "（インデックスは validate で検証されないため、ずれても本番は起動します）")
                // 順序を問わず過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(expected);
    }
}
