// ドメイン（JPA エンティティ）のテストパッケージ
package com.izumacha.expensetracker.domain;

// 主キーの採番方式（識別列かどうか）を読み取るためのアノテーション
import jakarta.persistence.GeneratedValue;
// 採番方式の種類を表す列挙（IDENTITY かどうかの判定に使う）
import jakarta.persistence.GenerationType;
// 主キーであることを判定するためのアノテーション
import jakarta.persistence.Id;
// エンティティのフィールドを走査するためのリフレクション型
import java.lang.reflect.Field;
// README を読むためのファイル入出力ユーティリティ
import java.nio.file.Files;
// README のパスを表す型
import java.nio.file.Path;
// 読み込み時の文字コードを明示するための型
import java.nio.charset.StandardCharsets;
// 解析結果を集める入れ物
import java.util.ArrayList;
// 重複していない名前を集めるための入れ物
import java.util.LinkedHashSet;
// 解析結果の一覧を扱うインターフェース
import java.util.List;
// 集合を扱うインターフェース
import java.util.Set;
// Hibernate が組み立てたマッピング情報（列名・型・インデックスの正本）
import org.hibernate.boot.Metadata;
// マッピング情報を組み立てる入口
import org.hibernate.boot.MetadataSources;
// Hibernate の各種サービスを保持するレジストリ
import org.hibernate.boot.registry.StandardServiceRegistry;
// 上記レジストリを組み立てるビルダ
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
// Hibernate の設定キー（方言・命名規則の指定に使う）
import org.hibernate.cfg.AvailableSettings;
// 本番と同じ PostgreSQL の方言（型名の決定に使う）
import org.hibernate.dialect.PostgreSQLDialect;
// マッピング情報から取り出す列
import org.hibernate.mapping.Column;
// マッピング情報から取り出すインデックス
import org.hibernate.mapping.Index;
// マッピング情報から取り出すテーブル
import org.hibernate.mapping.Table;
// マッピング情報から取り出す一意制約
import org.hibernate.mapping.UniqueKey;
// 全テストの前に 1 度だけ実行する準備メソッドを宣言するアノテーション
import org.junit.jupiter.api.BeforeAll;
// テストメソッドを宣言するアノテーション
import org.junit.jupiter.api.Test;

// 検証用の assertThat を取り込む（AssertJ）
import static org.assertj.core.api.Assertions.assertThat;

/**
 * README に載せた {@code audit_logs} の手書き DDL が、{@link AuditLog} のマッピングとずれていないことを
 * 機械的に保証する整合性テスト。
 *
 * <p>【何を守るテストか】本番のスキーマ方針は {@code ddl-auto: validate}（DDL を自動発行しない）
 * なので、既存の本番 DB へ監査ログを導入するときは README の DDL を<b>人手で適用する</b>。
 * README 自身が「両方を同じ PR で直してください」と書いているとおり、この写しは人の記憶だけで
 * 正本（{@link AuditLog}）に追随している。ずれると次の 2 通りに壊れる。
 *
 * <ul>
 *   <li><b>列のずれ</b>: 起動時の {@code validate} が食い違いを検出して<b>本番の起動が失敗する</b>。
 *       安全側に倒れるとはいえ、気付くのがデプロイの瞬間で、しかもローカル（{@code docker compose}）と
 *       Testcontainers はスキーマを自動生成するため<b>手元では絶対に再現しない</b>。</li>
 *   <li><b>インデックスのずれ</b>: {@code validate} はインデックスを検証しない。README への追記を
 *       忘れると、本番だけインデックスが無いまま<b>静かに</b>動き続ける。{@code audit_logs} は追記のみで
 *       際限なく増えるテーブルなので、参照が全件走査に落ちて後から効いてくる（共通規約 §8）。</li>
 * </ul>
 *
 * <p>前者は「起動が失敗する」ことで気付けるが後者は気付けない。どちらも、写しを人手で追随させる
 * かぎり必ず起こりうるため、{@code AuditedEntityCoverageTest} と同じ考え方で検出網を置く
 * ——人の付け忘れをビルドで止める。
 *
 * <h2>期待値は Hibernate 自身に作らせる</h2>
 * 「エンティティがどんなテーブルになるか」（列名・SQL 型・NULL 可否・インデックス）は
 * <b>Hibernate に組み立てさせたマッピング情報から読む</b>。この対応関係を自前で書き写すと、
 * 写し間違いがそのまま<b>誤った指示</b>になる——たとえば命名規則を自前で実装すると
 * {@code actorIP} のようなフィールドで Hibernate（{@code actorip}）と食い違い、
 * テストは README に {@code actor_i_p} と書けと指示し、それに従うと本番の {@code validate} が
 * 落ちる。<b>この検出網が防ぐはずの失敗を、検出網自身が引き起こす</b>ことになる。
 * 同じ理由で型の対応表も持たない（{@code columnDefinition} や {@code @Lob} を見落とす）。
 * Hibernate に聞けば、命名規則・型・{@code @Transient} の除外・関連の {@code @JoinColumn} まで
 * すべて本番と同じ答えが返る。
 *
 * <p>DB も Spring コンテキストも起動しない。Hibernate のマッピング組み立ては JDBC 接続なしで行う
 * （方言を明示し、接続からのメタデータ取得を無効化する）ため、Docker の有無に関わらず動く（§11）。
 */
class AuditLogReadmeDdlTest {

    /**
     * 読み取る README のパス。
     *
     * <p>Surefire はプロジェクト直下を作業ディレクトリにして実行するため相対パスで解決できる。
     */
    private static final Path README_PATH = Path.of("README.md");

    // Markdown のコードフェンス（コードブロックの終わりを示す）
    private static final String CODE_FENCE = "```";

    // SQL のコードブロックの開きフェンス（DDL が書かれている塊を見分けるために使う）
    private static final String SQL_CODE_FENCE = "```sql";

    // 以降は DDL の語彙。散らばると解釈できる書き方を増やすときに拾い漏れるため定数に集約する（§6）
    // テーブル定義の開始を示す語
    private static final String CREATE_TABLE_KEYWORD = "create table";
    // 再実行可能な DDL で使われる「既にあれば作らない」指定
    private static final String IF_NOT_EXISTS_KEYWORD = "if not exists";
    // 文の開始を示す語（インデックス定義の判別に使う）
    private static final String CREATE_KEYWORD = "create";
    // 一意インデックスであることを示す語
    private static final String UNIQUE_KEYWORD = "unique";
    // インデックス定義であることを示す語
    private static final String INDEX_KEYWORD = "index";
    // インデックスの対象テーブルを示す語
    private static final String ON_KEYWORD = "on";
    // NULL を許さないことを示す語
    private static final String NOT_NULL_KEYWORD = "not null";
    // 主キーであることを示す語
    private static final String PRIMARY_KEY_KEYWORD = "primary key";
    // DB 側で自動採番する識別列であることを示す語
    private static final String IDENTITY_KEYWORD = "generated by default as identity";

    /**
     * 列定義ではなく<b>表制約</b>の始まりを示す語。
     *
     * <p>{@code PRIMARY KEY (id)} のような表制約は列定義と同じくカンマ区切りで並ぶため、
     * 区別しないと {@code primary} という名前の列があることにされてしまう。
     */
    private static final Set<String> CONSTRAINT_KEYWORDS =
            Set.of("primary", "foreign", "unique", "check", "constraint", "exclude");

    /**
     * 列に直接書ける修飾子のうち、この検証が意味を理解できる語。
     *
     * <p>ここに無い語（{@code unique} / {@code check} / {@code references} など）が列に付いていたら、
     * 正本と突き合わせる術が無いということなので<b>黙って無視せず止める</b>。詳しい理由は
     * {@link #rejectUnsupported(String, String)} を参照。
     */
    private static final Set<String> SUPPORTED_COLUMN_MODIFIERS =
            Set.of("not", "null", "primary", "key", "generated", "by", "default", "as", "identity");

    /**
     * 列に直接書かれた制約を示す語（主キーを除く）。
     *
     * <p>型の名前が複数語になること（{@code timestamp(6) with time zone} など）があるため、
     * 知らない語をすべて拒否すると正しい型まで弾いてしまう。一方でこれらの語は型名には現れないので、
     * 列名より後ろのどこに現れても「この検証が扱えない制約」と判断してよい。
     */
    private static final Set<String> COLUMN_LEVEL_CONSTRAINT_KEYWORDS =
            Set.of("unique", "check", "references", "constraint", "foreign", "exclude");

    /**
     * テーブル 1 つ分のスキーマ（正本側と README 側を同じ形にそろえて突き合わせる）。
     *
     * @param tableName          テーブル名
     * @param columns            列の定義（宣言順）
     * @param primaryKeyColumns  主キーを構成する列名
     * @param indexes            インデックスの定義
     * @param identityColumns    識別列（自動採番）として定義された列名
     */
    private record Schema(String tableName,
                          List<ColumnDefinition> columns,
                          List<String> primaryKeyColumns,
                          List<IndexDefinition> indexes,
                          Set<String> identityColumns) {
    }

    /**
     * 列 1 つ分の定義。
     *
     * @param name    列名
     * @param sqlType SQL の型（方言つきの表記。例 {@code varchar(64)}）
     * @param notNull NULL を許さないか（主キーは制約上必ず非 NULL とみなす）
     */
    private record ColumnDefinition(String name, String sqlType, boolean notNull) {
    }

    /**
     * インデックス 1 つ分の定義。
     *
     * @param name    インデックス名
     * @param columns 対象の列名（定義された順）
     * @param unique  一意インデックスか
     */
    private record IndexDefinition(String name, List<String> columns, boolean unique) {
    }

    // 正本（Hibernate のマッピング情報）から組み立てたスキーマ
    private static Schema entitySchema;

    // README の手書き DDL から読み取ったスキーマ
    private static Schema readmeSchema;

    /** 両側のスキーマを 1 度だけ用意する（README は実行中に変わらないため読み直さない）。 */
    @BeforeAll
    static void loadSchemas() {
        // 正本側を Hibernate に組み立てさせる
        entitySchema = buildEntitySchema();
        // README 側を解析する（テーブル名は正本のものを手がかりに探す）
        readmeSchema = parseReadmeSchema(entitySchema.tableName());
    }

    // ------------------------------------------------------------------
    // 正本側（Hibernate のマッピング情報）
    // ------------------------------------------------------------------

    /**
     * {@link AuditLog} が本番でどんなテーブルになるかを、Hibernate に組み立てさせて読み取る。
     *
     * <p>本番と同じ方言・命名規則を明示的に与えることで、返る名前と型が本番の
     * {@code validate} が期待するものと一致する。JDBC 接続は張らない。
     */
    private static Schema buildEntitySchema() {
        // Hibernate のサービスレジストリを組み立てる
        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                // 本番と同じ PostgreSQL の方言を使う（型名はここで決まる）
                .applySetting(AvailableSettings.DIALECT, PostgreSQLDialect.class.getName())
                // DB へ接続してメタデータを取りに行かせない（接続不要でマッピングだけ組み立てる）。
                // キーは文字列で書かず定数を使う。Hibernate は知らない設定キーを黙って無視するため、
                // 綴り違いや将来の改名が「気付かないまま JDBC 接続を試みる」状態に戻してしまう
                .applySetting(AvailableSettings.ALLOW_METADATA_ON_BOOT, "false")
                // Spring Boot 3 の既定と同じ物理命名規則（キャメルケース→スネークケース）を使う
                .applySetting(AvailableSettings.PHYSICAL_NAMING_STRATEGY,
                        "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy")
                // Spring Boot の既定と同じ論理命名規則を使う
                .applySetting(AvailableSettings.IMPLICIT_NAMING_STRATEGY,
                        "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy")
                // 設定を確定してレジストリを作る
                .build();
        // レジストリは内部でスレッドや設定を保持するため、使い終わったら必ず解放する（§8）
        try {
            // 監査ログのエンティティだけを対象にマッピング情報を組み立てる
            Metadata metadata = new MetadataSources(registry)
                    // 対象のエンティティを登録する
                    .addAnnotatedClass(AuditLog.class)
                    // マッピング情報を確定する
                    .buildMetadata();
            // 組み立てた情報から目的のテーブルを取り出してスキーマへ変換する
            return toSchema(metadata, findTable(metadata));
        } finally {
            // レジストリを閉じて資源を解放する
            StandardServiceRegistryBuilder.destroy(registry);
        }
    }

    /**
     * 組み立てたマッピング情報から、監査ログのエンティティが束ねられているテーブルを取り出す。
     *
     * <p>名前空間の先頭のテーブルを取るのではなく<b>エンティティから辿る</b>。1 エンティティが
     * 複数のテーブルを生む場合（{@code @ElementCollection} / {@code @SecondaryTable} など）に
     * 先頭を取ると、どのテーブルが返るかが走査順まかせになり、副テーブルを掴んだ時点で
     * 「README にそのテーブルが無い」という<b>実際には正しい DDL を否定する</b>失敗になる。
     */
    private static Table findTable(Metadata metadata) {
        // エンティティ名からマッピングを引く
        var binding = metadata.getEntityBinding(AuditLog.class.getName());
        // 引けないのはマッピングの組み立てに失敗しているので握り潰さず失敗させる（§6）
        if (binding == null) {
            // 何が取れなかったかを添えて停止する
            throw new IllegalStateException("AuditLog のマッピングを取り出せませんでした");
        }
        // エンティティが束ねられている主テーブルを返す
        return binding.getTable();
    }

    /** Hibernate のテーブル情報を、README 側と突き合わせられる形へ変換する。 */
    private static Schema toSchema(Metadata metadata, Table table) {
        // 主キーを構成する列名を集める（主キーが無いことは想定しないが、あれば空のまま扱う）
        List<String> primaryKeyColumns = new ArrayList<>();
        // 主キーが定義されていれば列名を取り出す
        if (table.getPrimaryKey() != null) {
            // 主キーの列を 1 つずつ加える
            for (Column column : table.getPrimaryKey().getColumns()) {
                // 列名を小文字にそろえて加える
                primaryKeyColumns.add(column.getName().toLowerCase());
            }
        }
        // 列の定義を集める
        List<ColumnDefinition> columns = new ArrayList<>();
        // テーブルの列を 1 つずつ変換する
        for (Column column : table.getColumns()) {
            // 列名を小文字にそろえる
            String name = column.getName().toLowerCase();
            // 主キーの列は制約上つねに非 NULL になるため、Hibernate の nullable と併せて判定する
            boolean notNull = !column.isNullable() || primaryKeyColumns.contains(name);
            // 方言に応じた SQL 型（varchar(64) など）を取り出して加える
            columns.add(new ColumnDefinition(name, column.getSqlType(metadata).toLowerCase(), notNull));
        }
        // インデックスの定義を集める
        List<IndexDefinition> indexes = new ArrayList<>();
        // 一意でないインデックスを加える
        for (Index index : table.getIndexes().values()) {
            // 名前と対象列を取り出して加える（一意ではない）
            indexes.add(new IndexDefinition(
                    index.getName().toLowerCase(), columnNames(index.getColumns()), false));
        }
        // 一意インデックス（@Index(unique = true)）は別の入れ物に入るので、そちらも加える
        for (UniqueKey uniqueKey : table.getUniqueKeys().values()) {
            // 名前と対象列を取り出して加える（一意）
            indexes.add(new IndexDefinition(
                    uniqueKey.getName().toLowerCase(), columnNames(uniqueKey.getColumns()), true));
        }
        // 変換したスキーマを返す（識別列はマッピング情報から取れないので注釈から別途求める）
        return new Schema(table.getName().toLowerCase(), columns, primaryKeyColumns, indexes,
                identityColumnsFromAnnotations(primaryKeyColumns));
    }

    /** 列の一覧から名前だけを小文字で取り出す。 */
    private static List<String> columnNames(List<Column> columns) {
        // 名前を集める入れ物
        List<String> names = new ArrayList<>();
        // 列を 1 つずつ処理する
        for (Column column : columns) {
            // 名前を小文字にそろえて加える
            names.add(column.getName().toLowerCase());
        }
        // 集めた名前を返す
        return names;
    }

    /**
     * 識別列（DB 側で自動採番する列）として定義されているべき列名を求める。
     *
     * <p>採番方式はマッピング情報の列からは読み取れないため、ここだけは注釈を直接見る。
     * 対象は {@code @Id} かつ {@code @GeneratedValue(strategy = IDENTITY)} の列で、列名は
     * 自前で組み立てず Hibernate が決めた主キーの列名をそのまま使う（命名規則を写さないため）。
     *
     * <p><b>親クラスまで遡って探す</b>のは、主キーを {@code @MappedSuperclass} の共通基底へ
     * 切り出す（監査対象が増えたときにありがちな整理）と、宣言フィールドだけでは {@code @Id} が
     * 見えなくなるため。見えないと期待値が空になり、README 側の識別列指定が「余分」に見える。
     * 赤くなったテストを通す自然な手当ては README から識別列の指定を消すことだが、そうすると
     * 本番の主キーに既定値が無くなり、監査ログの挿入だけが常に失敗する——しかも書き込みは
     * fail-open なので API は正常に見える。まさにこの検証が防ぐはずの壊れ方を招く。
     */
    private static Set<String> identityColumnsFromAnnotations(List<String> primaryKeyColumns) {
        // 識別列の名前を集める入れ物
        Set<String> identityColumns = new LinkedHashSet<>();
        // エンティティ本体から親クラスへ順に遡って確認する
        for (Class<?> type = AuditLog.class; type != null && type != Object.class; type = type.getSuperclass()) {
            // フィールドとメソッドの両方を見る。
            // 【なぜメソッドも見るか】JPA は注釈をフィールドに付ける形（フィールドアクセス）と
            // ゲッターに付ける形（プロパティアクセス）の両方を認めている。フィールドだけを見ると、
            // ゲッターに付け替えられた時点で期待値が空になり、README の識別列指定が余分に見える。
            // 赤いテストを通す自然な手当ては README から指定を消すことだが、そうすると本番の
            // 主キーに既定値が無くなり監査ログの挿入だけが常に失敗する（fail-open なので気付けない）
            for (java.lang.reflect.AnnotatedElement member : annotatedMembers(type)) {
                // 主キーでなければ対象外
                if (!member.isAnnotationPresent(Id.class)) {
                    // 次のメンバへ進む
                    continue;
                }
                // 採番方式の指定を取り出す
                GeneratedValue generatedValue = member.getAnnotation(GeneratedValue.class);
                // DB 側の自動採番（IDENTITY）でなければ識別列にはならない
                if (generatedValue == null || generatedValue.strategy() != GenerationType.IDENTITY) {
                    // 次のメンバへ進む
                    continue;
                }
                // 単一列の主キーであることを前提に、Hibernate が決めた主キーの列名を識別列とする
                identityColumns.addAll(primaryKeyColumns);
            }
        }
        // 集めた識別列を返す
        return identityColumns;
    }

    /** 注釈が付きうるメンバ（フィールドとメソッド）をまとめて返す。 */
    private static List<java.lang.reflect.AnnotatedElement> annotatedMembers(Class<?> type) {
        // メンバを集める入れ物
        List<java.lang.reflect.AnnotatedElement> members = new ArrayList<>();
        // そのクラスが宣言しているフィールドを加える
        for (Field field : type.getDeclaredFields()) {
            // フィールドを加える
            members.add(field);
        }
        // そのクラスが宣言しているメソッド（ゲッター）を加える
        for (java.lang.reflect.Method method : type.getDeclaredMethods()) {
            // メソッドを加える
            members.add(method);
        }
        // 集めたメンバを返す
        return members;
    }

    // ------------------------------------------------------------------
    // README 側の読み取り
    // ------------------------------------------------------------------

    /**
     * README の手書き DDL を読み取り、正本と同じ形のスキーマにして返す。
     *
     * <p><b>ブロックの中身は 1 文残らず見る</b>。以前は「{@code create table} の位置から読み始める」
     * 実装だったため、その<b>手前</b>に置かれた文（{@code ALTER TABLE ... ADD CONSTRAINT} など）が
     * 誰にも見られないまま通っていた。同じ文が後ろにあれば拒否されるのに前にあれば通る、という
     * 位置任せの穴だったので、ブロック全体を文に分けてから種類ごとに振り分ける。
     */
    private static Schema parseReadmeSchema(String expectedTableName) {
        // DDL ブロックを切り出す（小文字にそろえてあるので以降は大小文字を気にしない）
        String block = readDdlBlock(expectedTableName);
        // テーブル定義の本体（括弧の内側）と、インデックス定義の文を仕分ける
        String tableBody = null;
        // インデックス定義の文だけを集める入れ物
        List<String> indexStatements = new ArrayList<>();
        // ブロックを「;」で文に分けて 1 つずつ振り分ける
        for (String rawStatement : block.split(";")) {
            // 前後の空白を落とす
            String statement = rawStatement.trim();
            // 空の断片は読み飛ばす
            if (statement.isEmpty()) {
                // 次の文へ進む
                continue;
            }
            // テーブル定義なら括弧の内側を取り出して覚えておく
            if (statement.startsWith(CREATE_TABLE_KEYWORD)) {
                // 列定義を囲む丸括弧の開き位置を求める
                int tableOpen = statement.indexOf('(');
                // 対応する閉じ括弧を求める
                int tableClose = matchingParenthesis(statement, tableOpen);
                // 括弧の内側を本体として覚えておく
                tableBody = statement.substring(tableOpen + 1, tableClose);
                // 次の文へ進む
                continue;
            }
            // インデックス定義なら後でまとめて解析する
            if (statement.startsWith(CREATE_KEYWORD)) {
                // 文を覚えておく
                indexStatements.add(statement);
                // 次の文へ進む
                continue;
            }
            // どちらでもない文（ALTER TABLE ... ADD CONSTRAINT / DROP など）は
            // 正本と突き合わせる術が無い。読み飛ばすと制約の追加が素通りするので止める
            rejectUnsupported("インデックス定義以外の文", statement);
        }
        // テーブル定義が見つからないのは、切り出しが壊れているということなので握り潰さず失敗させる
        if (tableBody == null) {
            // 何が無かったかを示して停止する
            throw new IllegalStateException("README の DDL ブロックに " + expectedTableName + " のテーブル定義がありません");
        }
        // 列の定義を集める入れ物
        List<ColumnDefinition> columns = new ArrayList<>();
        // 主キーを構成する列名を集める入れ物
        List<String> primaryKeyColumns = new ArrayList<>();
        // 識別列の名前を集める入れ物
        Set<String> identityColumns = new LinkedHashSet<>();
        // 括弧の内側をカンマで区切り、1 項目ずつ処理する
        for (String rawItem : splitTopLevel(tableBody)) {
            // 型の括弧の中にある空白を落として、語の分割で型が割れないようにする
            String item = removeWhitespaceInsideParentheses(rawItem.trim());
            // 空の項目（末尾のカンマなど）は読み飛ばす
            if (item.isEmpty()) {
                // 次の項目へ進む
                continue;
            }
            // 空白の連続で語に分ける
            String[] tokens = item.split("\\s+");
            // 先頭の語が制約の語なら、これは列ではなく表制約（PRIMARY KEY (id) など）
            if (CONSTRAINT_KEYWORDS.contains(tokens[0])) {
                // 主キーは対象列を拾って比較に使う。
                // 判定には語をつなぎ直した文字列を使う（元の文字列のままだと、改行や空白 2 つで
                // 区切った `PRIMARY\n    KEY (id)` という正しい書き方を「扱えない制約」として
                // 落としてしまい、しかも直しようのない指示を出すことになる）
                if (String.join(" ", tokens).startsWith(PRIMARY_KEY_KEYWORD)) {
                    // 制約が囲む列名を主キーとして加える
                    primaryKeyColumns.addAll(parseColumnList(item));
                    // 次の項目へ進む
                    continue;
                }
                // 主キー以外の表制約は、この検証が正本側と突き合わせる術を持たない。
                // 読み飛ばすとエンティティに無い制約が本番だけに入り、監査記録が静かに欠ける
                rejectUnsupported("表制約", item);
            }
            // 列名と型の 2 語は最低限必要なので、足りなければ解析できていない
            assertThat(tokens.length)
                    // 失敗時にどの定義でつまずいたかを示す
                    .as("列定義を解析できません（列名と型が読み取れません）: %s", item)
                    // 2 語以上あることを検証する
                    .isGreaterThanOrEqualTo(2);
            // 1 語目が列名
            String name = tokens[0];
            // 2 語目以降のうち、修飾子が始まる手前までが型。
            // 【なぜ 1 語と決め打たないか】`timestamp(6) with time zone` や `double precision` の
            // ように型が複数語になることがある。1 語目だけを型とすると、残りが修飾子に混ざって
            // <b>どう書いても一致しない</b>状態になり、通す唯一の方法が「README から型の一部を
            // 削る」＝本番の validate を落とす修正になってしまう
            int modifierStart = indexOfFirstModifier(tokens);
            // 型の語をつないで 1 つの型名にする（Hibernate 側も空白区切りで返す）
            String sqlType = String.join(" ", java.util.Arrays.copyOfRange(tokens, 1, modifierStart));
            // 修飾子の語をつなぐ
            String modifiers = String.join(" ", java.util.Arrays.copyOfRange(tokens, modifierStart, tokens.length));
            // 列に直接書かれた制約（UNIQUE / CHECK / REFERENCES など）が無いか、列名より後ろを全部見る。
            // 型に吸収されて「型が違う」という分かりにくい失敗になるのを防ぎ、原因を名指しする
            for (int i = 1; i < tokens.length; i++) {
                // 制約の語であれば、正本と突き合わせられないので止める
                if (COLUMN_LEVEL_CONSTRAINT_KEYWORDS.contains(tokens[i])) {
                    // 何が扱えないかを示して停止する
                    rejectUnsupported("列 " + name + " に直接書かれた制約「" + tokens[i] + "」", item);
                }
            }
            // 修飾子として読み始めた後は、知っている語しか許さない。
            // 【なぜ必要か】修飾子をひとつなぎの文字列にして「NOT NULL を含むか」だけを見ると、
            // その先に続く未知の指定（`DEFAULT now()` や `GENERATED ALWAYS AS (...) STORED` など）を
            // 黙って読み飛ばしてしまう。正本と突き合わせていない指定が本番の DDL に入るのに
            // 検証は緑のまま、という「範囲外は落とす」という約束を破った状態になる
            for (int i = modifierStart; i < tokens.length; i++) {
                // 知っている修飾子でなければ、正本と突き合わせられないので止める
                if (!SUPPORTED_COLUMN_MODIFIERS.contains(tokens[i])) {
                    // 何が扱えないかを示して停止する
                    rejectUnsupported("列 " + name + " に付いた指定「" + tokens[i] + "」", item);
                }
            }
            // 列に直接書かれた主キー指定は、表制約と同じく主キーの構成列になる
            if (modifiers.contains(PRIMARY_KEY_KEYWORD)) {
                // 主キーの列として加える
                primaryKeyColumns.add(name);
            }
            // 識別列の指定があれば覚えておく
            if (modifiers.contains(IDENTITY_KEYWORD)) {
                // 識別列として加える
                identityColumns.add(name);
            }
            // 解析した 1 列分を加える。
            // NULL 可否はここでは「NOT NULL と書かれているか」だけを持たせ、主キーによる
            // 非 NULL は下の 2 周目で反映する
            columns.add(new ColumnDefinition(name, sqlType, modifiers.contains(NOT_NULL_KEYWORD)));
        }
        // インデックス定義を解析する
        List<IndexDefinition> indexes = parseIndexes(indexStatements, expectedTableName);
        // 読み取ったスキーマを返す（主キーの反映を終えた列を渡す）
        return new Schema(expectedTableName, applyPrimaryKeyNotNull(columns, primaryKeyColumns),
                primaryKeyColumns, indexes, identityColumns);
    }

    /**
     * 主キーを構成する列を非 NULL として確定させる。
     *
     * <p><b>なぜ列の解析と分けるのか</b>: 主キーは列に直接書く形（{@code id BIGINT PRIMARY KEY}）
     * だけでなく、すべての列の後ろに表制約として書く形（{@code PRIMARY KEY (id)}）も正しい DDL。
     * 後者では {@code id} を読んだ時点ではまだ主キーだと分からないため、1 周目で判定すると
     * <b>正しい DDL なのに「NOT NULL がずれている」と誤って落ちる</b>。全項目を読み終えてから
     * まとめて反映する。
     */
    private static List<ColumnDefinition> applyPrimaryKeyNotNull(
            List<ColumnDefinition> columns, List<String> primaryKeyColumns) {
        // 反映後の列を集める入れ物
        List<ColumnDefinition> resolved = new ArrayList<>();
        // 読み取った列を 1 つずつ確認する
        for (ColumnDefinition column : columns) {
            // NOT NULL と書かれているか、主キーの構成列なら非 NULL とする
            boolean notNull = column.notNull() || primaryKeyColumns.contains(column.name());
            // NULL 可否を確定させた列を加える
            resolved.add(new ColumnDefinition(column.name(), column.sqlType(), notNull));
        }
        // 反映後の列を返す
        return resolved;
    }

    /**
     * README から DDL のコードブロックを切り出し、小文字にそろえて返す。
     *
     * <p><b>探し方</b>: README 中の {@code create table} をすべて見て、テーブル名が正本と
     * <b>完全一致</b>する文を採用する。README に別のテーブルの DDL が増えても取り違えず、逆に
     * README 側でテーブル名を変えた（＝正本とずれた）場合は「見つからない」として落ちる。
     * 前方一致で探すと {@code audit_logs_v2} のような別名を掴んでしまい、テーブル名のずれを
     * 検出できなくなる。再実行可能にするための {@code if not exists} が付いていても読める。
     */
    private static String readDdlBlock(String expectedTableName) {
        // README を読む（存在しない・読めないのは環境の異常なので握り潰さず失敗させる。§6）
        String readme;
        try {
            // UTF-8 として README 全体を読み込み、以降の解析のため小文字にそろえる。
            // SQL のキーワードも引用符なしの識別子も大小文字を区別しないため、これで意味は変わらない
            readme = Files.readString(README_PATH, StandardCharsets.UTF_8).toLowerCase();
        } catch (java.io.IOException e) {
            // どのファイルが読めなかったかを添えて停止する
            throw new IllegalStateException("README を読み取れません: " + README_PATH.toAbsolutePath(), e);
        }
        // README 内の SQL コードブロックのうち、対象テーブルに言及しているものを集める。
        // 【なぜブロック単位で数えるか】README は日英 2 言語なので、同じ DDL が別の場所へ写される
        // ことがありうる。「create table の個数」だけを数えていると、索引定義だけを写した
        // 2 つ目のブロック（`CREATE INDEX ... ON audit_logs (...)` だけの塊）が誰にも検証されない
        // まま古くなり、それを見た運用者が本番に誤った索引を作る。ブロック単位で見れば、
        // どんな形の写しでも「対象テーブルに触れる SQL ブロックは 1 つだけ」で捕まえられる
        List<String> blocks = new ArrayList<>();
        // SQL コードブロックの開き位置を探す
        int fence = readme.indexOf(SQL_CODE_FENCE);
        // 見つからなくなるまで 1 ブロックずつ確認する
        while (fence >= 0) {
            // 開きフェンスの行末（＝中身の開始位置）を探す
            int contentStart = readme.indexOf('\n', fence);
            // 行末が無ければ壊れているので打ち切る
            if (contentStart < 0) {
                // 探索を終える
                break;
            }
            // 閉じフェンスを探す
            int contentEnd = readme.indexOf(CODE_FENCE, contentStart);
            // 閉じフェンスが無ければ Markdown が壊れているので失敗させる
            assertThat(contentEnd)
                    // 失敗時に何が起きたかを示す
                    .as("README の SQL ブロックを閉じるコードフェンス（%s）が見つかりません", CODE_FENCE)
                    // 見つかった位置は 0 以上になる
                    .isNotNegative();
            // 中身を取り出す
            String content = readme.substring(contentStart + 1, contentEnd);
            // 対象テーブルに言及しているブロックだけを候補に加える
            if (content.contains(expectedTableName)) {
                // 中身を候補に加える
                blocks.add(content);
            }
            // 次の SQL ブロックを探す
            fence = readme.indexOf(SQL_CODE_FENCE, contentEnd);
        }
        // 対象テーブルに触れる SQL ブロックが無い＝本番への適用手順が失われている
        if (blocks.isEmpty()) {
            // 何が無くて、どう直せばよいかを示して停止する
            throw new IllegalStateException(
                    "README に " + expectedTableName + " の DDL が見つかりません"
                            + "（本番へ手動適用する DDL が失われていないか、テーブル名が @Table とずれていないか確認してください）");
        }
        // 写しが増えると検証されない方が古くなるので、1 つだけであることを確かめる
        assertThat(blocks)
                // 失敗時に何が起きているかと直し方を示す
                .as("README に %s に触れる SQL ブロックが複数あります"
                        + "（写しが増えると検証されない方が古くなります。1 箇所にまとめてください）",
                        expectedTableName)
                // 写しが 1 つだけであることを検証する
                .hasSize(1);
        // 唯一のブロックからコメントを落として返す
        String block = removeLineComments(blocks.get(0));
        // 対象テーブルのテーブル定義が含まれていることを確かめる（索引だけの写しを本体と誤認しない）
        assertThat(block)
                // 失敗時に何が無いかを示す
                .as("README の SQL ブロックに %s %s がありません", CREATE_TABLE_KEYWORD, expectedTableName)
                // テーブル定義が含まれることを検証する
                .contains(CREATE_TABLE_KEYWORD);
        // 解析対象のブロックを返す
        return block;
    }

    /**
     * SQL の行コメント（{@code --} から行末まで）を取り除く。
     *
     * <p>README は本番へ適用する手順書なので、列や索引の意図をコメントで補うのは自然な編集。
     * 落とさずに解析すると、コメント付きの<b>正しい</b> DDL が「列がずれている」「索引が足りない」
     * として落ち、書いた人は存在しないずれを直そうとすることになる。この検出網が防ぐはずの
     * 「誤った指示」を自ら出さないために、解析の前に取り除く。
     */
    private static String removeLineComments(String ddl) {
        // 組み立て先のバッファ
        StringBuilder stripped = new StringBuilder(ddl.length());
        // 行ごとに処理する（コメントは行末までなので行単位で足りる）
        for (String line : ddl.split("\n", -1)) {
            // コメントの開始位置を探す
            int comment = line.indexOf("--");
            // コメントがあればその手前まで、無ければ行全体を残す
            stripped.append(comment >= 0 ? line.substring(0, comment) : line)
                    // 行の区切りを戻す
                    .append('\n');
        }
        // コメントを落とした DDL を返す
        return stripped.toString();
    }

    /**
     * インデックス定義（{@code create index} / {@code create unique index}）をすべて解析して返す。
     *
     * <p>一意インデックスも読めるようにしてあるのは、{@code @Index(unique = true)} を足したときに
     * 正しい README の書き方がこの検証を通せないと、<b>まっとうなスキーマ変更のたびにテスト側を
     * 直さないと進めなくなる</b>ため。逆向き（README にだけ一意インデックスが残る）も見逃さない。
     */
    private static List<IndexDefinition> parseIndexes(List<String> statements, String expectedTableName) {
        // 解析結果を集める入れ物
        List<IndexDefinition> indexes = new ArrayList<>();
        // 仕分け済みのインデックス定義を 1 つずつ処理する
        for (String statement : statements) {
            // 対象列を囲む丸括弧の開き位置を探す
            int open = statement.indexOf('(');
            // 開き括弧が無ければ文の形が想定と違うので失敗させる
            assertThat(open)
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義の対象列を囲む丸括弧が見つかりません: %s", statement)
                    // 見つかった位置は 0 以上になる
                    .isNotNegative();
            // 「create [unique] index <名前> [if not exists] on <テーブル>」の部分を語に分ける
            String head = statement.substring(0, open).trim();
            // 再実行可能にするための指定は解析の邪魔になるので取り除く
            String normalizedHead = head.replace(IF_NOT_EXISTS_KEYWORD, " ").trim();
            // 語に分ける
            String[] tokens = normalizedHead.split("\\s+");
            // 2 語目が unique なら一意インデックス（以降の語の位置が 1 つずれる）
            boolean unique = tokens.length > 1 && tokens[1].equals(UNIQUE_KEYWORD);
            // unique の有無による語の位置ずれ
            int offset = unique ? 1 : 0;
            // create / [unique] / index / 名前 / on / テーブル名 の語数を検証する
            assertThat(tokens.length)
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義を解析できません: %s", statement)
                    // unique の有無に応じた語数であることを検証する
                    .isEqualTo(5 + offset);
            // index という語が想定の位置にあることを検証する
            assertThat(tokens[1 + offset])
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義として解釈できない文です: %s", statement)
                    // index であることを検証する
                    .isEqualTo(INDEX_KEYWORD);
            // on という語が想定の位置にあることを検証する
            assertThat(tokens[3 + offset])
                    // 失敗時にどの文でつまずいたかを示す
                    .as("インデックス定義として解釈できない文です: %s", statement)
                    // on であることを検証する
                    .isEqualTo(ON_KEYWORD);
            // インデックスが正本のテーブルに向いていることを検証する
            assertThat(tokens[4 + offset])
                    // 失敗時にどのテーブルへ向いていたかを示す
                    .as("インデックス %s が別のテーブルに向いています: %s", tokens[2 + offset], statement)
                    // 対象テーブル名が一致することを検証する
                    .isEqualTo(expectedTableName);
            // 対象列を読み取る
            List<String> indexColumns = parseColumnList(statement);
            // 並び順の指定（DESC / ASC）や演算子クラスが付いていないか確かめる。
            // 正本側は列名しか持たないため、付いたまま比較すると「同じ索引」と誤って通してしまう
            for (String indexColumn : indexColumns) {
                // 列名に空白が残っていれば、それは列名以外の指定が付いているということ
                if (indexColumn.contains(" ")) {
                    // 何が扱えないかを示して停止する
                    rejectUnsupported("索引の列に付いた指定「" + indexColumn + "」", statement);
                }
            }
            // 解析した 1 つ分を加える
            indexes.add(new IndexDefinition(tokens[2 + offset], indexColumns, unique));
        }
        // 解析結果を返す
        return indexes;
    }

    /**
     * 列定義の語の並びから、型が終わって修飾子が始まる位置を返す。
     *
     * <p>型が何語になるかは方言しだいなので「型を数える」のではなく「修飾子の始まりを探す」。
     * 知っている修飾子の語が現れた最初の位置までが型で、見つからなければ全部が型。
     */
    private static int indexOfFirstModifier(String[] tokens) {
        // 列名（0 番目）と型の 1 語目（1 番目）は必ず型側なので 2 番目から探す
        for (int i = 2; i < tokens.length; i++) {
            // 知っている修飾子の語が現れたら、そこが修飾子の始まり
            if (SUPPORTED_COLUMN_MODIFIERS.contains(tokens[i])) {
                // その位置を返す
                return i;
            }
        }
        // 修飾子が見つからなければ、末尾までが型
        return tokens.length;
    }

    /**
     * この検証が意味を理解できない DDL に出会ったときに、黙って見逃さず止める。
     *
     * <p><b>なぜ読み飛ばさないか</b>: 読み飛ばすと、正本に無いものを README に書いても素通りする。
     * たとえばエンティティに無い一意制約（表制約でも列に直接書く形でも）を足すと、同じ行への
     * 2 度目の記録（{@code CREATE} のあとの {@code UPDATE}）が制約に弾かれる。監査ログの書き込みは
     * fail-open なので WARN だけ出して記録が落ち、{@code validate} も制約は見ないため、
     * <b>どこにも合図が出ないまま監査証跡が欠ける</b>。この検出網が防ぐはずの壊れ方そのものなので、
     * 扱えないものは通さず、検証を広げるよう促して止める。
     */
    private static void rejectUnsupported(String what, String statement) {
        // 何が扱えなくて、どうすればよいかを示して停止する
        throw new IllegalStateException(
                "README の DDL に、この検証が扱えない記述が含まれています（" + what + "）: " + statement.trim()
                        + "（正本側と突き合わせる方法を AuditLogReadmeDdlTest に追加してください）");
    }

    /** 丸括弧に囲まれた列名の並び（{@code (a, b)}）を取り出して返す。 */
    private static List<String> parseColumnList(String text) {
        // 開き括弧の位置を探す
        int open = text.indexOf('(');
        // 対応する閉じ括弧の位置を探す
        int close = matchingParenthesis(text, open);
        // 列名を集める入れ物
        List<String> columns = new ArrayList<>();
        // 括弧の内側をカンマで区切って 1 つずつ加える
        for (String column : splitTopLevel(text.substring(open + 1, close))) {
            // 前後の空白を落として加える
            columns.add(column.trim());
        }
        // 集めた列名を返す
        return columns;
    }

    /**
     * {@code open} の位置にある開き括弧に対応する閉じ括弧の位置を返す。
     *
     * <p>単純に最初の {@code ')'} を探すと、{@code numeric(10,2)} のように型が括弧を持つ列が
     * 増えたときに途中で切れる。深さを数えて対応する側を見つける。
     */
    private static int matchingParenthesis(String text, int open) {
        // 開き括弧が見つかっていない場合は解析できないので失敗させる
        assertThat(open)
                // 失敗時に何が起きたかを示す
                .as("丸括弧が見つかりません: %s", text)
                // 見つかった位置は 0 以上になる
                .isNotNegative();
        // 括弧の深さ（開き括弧で増やし閉じ括弧で減らす）
        int depth = 0;
        // 開き括弧の位置から末尾まで 1 文字ずつ走査する
        for (int i = open; i < text.length(); i++) {
            // 現在位置の文字を取り出す
            char c = text.charAt(i);
            // 開き括弧なら深さを 1 つ増やす
            if (c == '(') {
                // 深さを増やす
                depth++;
            } else if (c == ')') {
                // 閉じ括弧なら深さを 1 つ減らす
                depth--;
                // 深さが 0 に戻った位置が対応する閉じ括弧
                if (depth == 0) {
                    // その位置を返す
                    return i;
                }
            }
        }
        // 対応する閉じ括弧が無いのは DDL が壊れているので握り潰さず失敗させる（§6）
        throw new IllegalStateException("対応する閉じ括弧が見つかりません: " + text.substring(open));
    }

    /**
     * 括弧の深さ 0 にあるカンマだけで文字列を区切って返す。
     *
     * <p>{@code String.split(",")} だと型の中のカンマ（{@code numeric(10,2)}）でも切れてしまうため、
     * 深さを見ながら自前で区切る。
     */
    private static List<String> splitTopLevel(String text) {
        // 区切った結果を集める入れ物
        List<String> parts = new ArrayList<>();
        // 括弧の深さ
        int depth = 0;
        // 直前の区切り位置
        int start = 0;
        // 先頭から末尾まで 1 文字ずつ走査する
        for (int i = 0; i < text.length(); i++) {
            // 現在位置の文字を取り出す
            char c = text.charAt(i);
            // 開き括弧なら深さを増やす
            if (c == '(') {
                // 深さを増やす
                depth++;
            } else if (c == ')') {
                // 閉じ括弧なら深さを減らす
                depth--;
            } else if (c == ',' && depth == 0) {
                // 深さ 0 のカンマは要素の区切りなので、そこまでを 1 要素として切り出す
                parts.add(text.substring(start, i));
                // 次の要素の開始位置を更新する
                start = i + 1;
            }
        }
        // 最後の区切りから末尾までを最終要素として加える
        parts.add(text.substring(start));
        // 区切った結果を返す
        return parts;
    }

    /**
     * 丸括弧の内側にある空白だけを取り除く。
     *
     * <p>{@code numeric(10, 2)} のように型の引数が空白で区切られていると、語の分割で型が
     * 2 つに割れて読めなくなる。Hibernate 側は空白なしで返すため、比較できる形にそろえる。
     */
    private static String removeWhitespaceInsideParentheses(String text) {
        // 組み立て先のバッファ
        StringBuilder normalized = new StringBuilder(text.length());
        // 括弧の深さ
        int depth = 0;
        // 先頭から末尾まで 1 文字ずつ走査する
        for (int i = 0; i < text.length(); i++) {
            // 現在位置の文字を取り出す
            char c = text.charAt(i);
            // 開き括弧なら深さを増やす
            if (c == '(') {
                // 深さを増やす
                depth++;
            } else if (c == ')') {
                // 閉じ括弧なら深さを減らす
                depth--;
            }
            // 括弧の内側の空白だけを落とし、それ以外はそのまま残す
            if (depth > 0 && Character.isWhitespace(c)) {
                // この文字は加えずに次へ進む
                continue;
            }
            // 文字を加える
            normalized.append(c);
        }
        // そろえた文字列を返す
        return normalized.toString();
    }

    // ------------------------------------------------------------------
    // 検証
    // ------------------------------------------------------------------

    // 両側の読み取りが機能していること（空振りで素通りしていないこと）を検証する
    @Test
    void 正本とREADMEの両方からスキーマを読み取れている() {
        // 正本側の列が読み取れていることを検証する。
        // 【なぜ先に確かめるか】どちらかが空のまま素通りすると、以降の「一致している」検証が
        // 「対象なし」で常に成功し、検出網そのものが死んでいることに気付けなくなる
        assertThat(entitySchema.columns())
                // 失敗時に何が起きたかを示す
                .as("AuditLog のマッピングから列を読み取れませんでした")
                // 少なくとも 1 列は読み取れていることを検証する
                .isNotEmpty();
        // README 側の列が読み取れていることを検証する
        assertThat(readmeSchema.columns())
                // 失敗時に何が起きたかを示す
                .as("README の DDL から列定義を読み取れませんでした")
                // 少なくとも 1 列は読み取れていることを検証する
                .isNotEmpty();
        // 正本側のインデックスが読み取れていることを検証する
        assertThat(entitySchema.indexes())
                // 失敗時に何が起きたかを示す
                .as("AuditLog のマッピングからインデックスを読み取れませんでした")
                // 少なくとも 1 つは読み取れていることを検証する
                .isNotEmpty();
    }

    // 列が名前・型・NULL 可否まで含めて過不足なく一致することを検証する
    @Test
    void READMEのDDLの列が正本と一致する() {
        // 【なぜ過不足の両方を見るか】足りない列は validate で起動失敗になり、余分な列は
        // validate を素通りして使われない列が本番だけに残り続ける。
        // なお containsExactlyInAnyOrder は個数まで見る比較なので、同じ列を 2 度書いた
        // README（PostgreSQL が適用時に拒否する）もここで落ちる
        assertThat(readmeSchema.columns())
                // 失敗時に何が起きているかと直し方を示す
                .as("README の DDL の列が AuditLog のマッピングと一致しません"
                        + "（列を変えたら README「監査ログの確認」の DDL も同じ PR で直してください）")
                // 順序を問わず過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(entitySchema.columns());
    }

    // 主キーが一致し、自動採番の識別列として定義されていることを検証する
    @Test
    void READMEのDDLの主キーが正本と一致し識別列になっている() {
        // 主キーを構成する列が一致することを検証する
        assertThat(readmeSchema.primaryKeyColumns())
                // 失敗時に何が起きているかを示す
                .as("README の DDL の主キーが AuditLog のマッピングと一致しません")
                // 順序を問わず過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(entitySchema.primaryKeyColumns());
        // 識別列（自動採番）の指定が一致することを検証する。
        // 【なぜ確かめるか】@GeneratedValue(IDENTITY) は DB 側の採番が前提で、識別列でないと
        // 挿入時に主キーが埋まらず、監査ログの書き込みだけが本番で落ちる（しかも fail-open なので
        // WARN が出るだけで API は正常に見える）
        assertThat(readmeSchema.identityColumns())
                // 失敗時に何が足りないかを示す
                .as("README の DDL の識別列（%s）が AuditLog の @GeneratedValue と一致しません",
                        IDENTITY_KEYWORD)
                // 過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(entitySchema.identityColumns());
    }

    // インデックスが名前・対象列・一意指定まで含めて過不足なく一致することを検証する
    @Test
    void READMEのDDLのインデックスが正本と一致する() {
        // 【なぜ過不足の両方を見るか】ddl-auto: validate はインデックスを検証しないため、
        // ここでずれても本番は起動してしまう。追記漏れは全件走査に、消し忘れは不要な
        // 書き込みコストになり、どちらも実行時には何の合図も出ない
        assertThat(readmeSchema.indexes())
                // 失敗時に何が起きているかと直し方を示す
                .as("README の DDL のインデックスが AuditLog のマッピングと一致しません"
                        + "（インデックスは validate で検証されないため、ずれても本番は起動します）")
                // 順序を問わず過不足なく一致することを検証する
                .containsExactlyInAnyOrderElementsOf(entitySchema.indexes());
    }
}
